// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh4LwP5ptOXueDM_VjSQLfU3rvXHp236Q',
    appId: '1:269280104893:web:9a71ffc39285f8573242d4',
    messagingSenderId: '269280104893',
    projectId: 'flutter-auth-app-c9838',
    authDomain: 'flutter-auth-app-c9838.firebaseapp.com',
    storageBucket: 'flutter-auth-app-c9838.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5-pYU0cPHGwPRedv-y77ByJ2ozwB9XhQ',
    appId: '1:269280104893:android:933349296b0a52823242d4',
    messagingSenderId: '269280104893',
    projectId: 'flutter-auth-app-c9838',
    storageBucket: 'flutter-auth-app-c9838.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnyWzSA1-8yRTMuC6Z1YEe3UobTKLCsdk',
    appId: '1:269280104893:ios:4362068bac5926503242d4',
    messagingSenderId: '269280104893',
    projectId: 'flutter-auth-app-c9838',
    storageBucket: 'flutter-auth-app-c9838.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnyWzSA1-8yRTMuC6Z1YEe3UobTKLCsdk',
    appId: '1:269280104893:ios:4362068bac5926503242d4',
    messagingSenderId: '269280104893',
    projectId: 'flutter-auth-app-c9838',
    storageBucket: 'flutter-auth-app-c9838.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh4LwP5ptOXueDM_VjSQLfU3rvXHp236Q',
    appId: '1:269280104893:web:46e4a9a46896a0cf3242d4',
    messagingSenderId: '269280104893',
    projectId: 'flutter-auth-app-c9838',
    authDomain: 'flutter-auth-app-c9838.firebaseapp.com',
    storageBucket: 'flutter-auth-app-c9838.firebasestorage.app',
  );
}
